language: cpp

dist: trusty
sudo: required


matrix:
  include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: g++-4.8
    before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -q
      - sudo apt-get install g++-4.8 -y
      - cd build
      - g++-4.8 -std=c++11 test.cpp
  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: g++-4.9
    before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -q
      - sudo apt-get install g++-4.9 -y
      - cd build
      - g++-4.9 -std=c++11 test.cpp
  - os: linux
    compiler: gcc
    env: COMPILER=g++-5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: g++-5
    before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -q
      - sudo apt-get install g++-5 -y
      - cd build
      - g++-5 -std=c++11 test.cpp
      
  - os: linux
    compiler: gcc
    env: COMPILER=g++-6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: g++-6
    before_script:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get update -q
      - sudo apt-get install g++-6 -y
      - cd build
      - g++-6 -std=c++11 test.cpp
      
  - os: linux
    compiler: clang
    env: COMPILER=clang++
    before_script:
      - cd build
      - clang++ -std=c++11 test2.cpp

  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
        packages: ['clang-3.5']
    env: COMPILER=clang++-3.5
    before_script:
      - cd build
      - clang++-3.5 -std=c++11 test2.cpp
      - clang++-3.5 --version

  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['clang-3.6']
    env: COMPILER=clang++-3.6
    before_script:
      - cd build
      - clang++-3.6 -std=c++11 test2.cpp
      - /usr/bin/clang++-3.6  --version
        		
  
script: 
  - $CXX --version
